-- Read-only exact row counts for public tables; table names and counts only.
SELECT 'asd' AS table_name, count(*) AS rows FROM public.asd
UNION ALL SELECT 'profiles', count(*) FROM public.profiles
UNION ALL SELECT 'completed_modules', count(*) FROM public.completed_modules
UNION ALL SELECT 'badges', count(*) FROM public.badges
UNION ALL SELECT 'review_items', count(*) FROM public.review_items
UNION ALL SELECT 'forum_posts', count(*) FROM public.forum_posts
UNION ALL SELECT 'forum_comments', count(*) FROM public.forum_comments
UNION ALL SELECT 'forum_likes', count(*) FROM public.forum_likes
UNION ALL SELECT 'game_results', count(*) FROM public.game_results
UNION ALL SELECT 'push_subscriptions', count(*) FROM public.push_subscriptions
UNION ALL SELECT 'friendships', count(*) FROM public.friendships
UNION ALL SELECT 'challenges', count(*) FROM public.challenges
UNION ALL SELECT 'login_history', count(*) FROM public.login_history
UNION ALL SELECT 'forum_poll_votes', count(*) FROM public.forum_poll_votes
UNION ALL SELECT 'courses', count(*) FROM public.courses
UNION ALL SELECT 'course_worlds', count(*) FROM public.course_worlds
UNION ALL SELECT 'lessons', count(*) FROM public.lessons
UNION ALL SELECT 'lesson_modules', count(*) FROM public.lesson_modules
UNION ALL SELECT 'smazzate', count(*) FROM public.smazzate
UNION ALL SELECT 'glossary', count(*) FROM public.glossary
UNION ALL SELECT 'asd_clubs', count(*) FROM public.asd_clubs
UNION ALL SELECT 'collectible_cards', count(*) FROM public.collectible_cards
UNION ALL SELECT 'weekly_challenges', count(*) FROM public.weekly_challenges
UNION ALL SELECT 'guided_hands', count(*) FROM public.guided_hands
UNION ALL SELECT 'eserciziario_exercises', count(*) FROM public.eserciziario_exercises
UNION ALL SELECT 'trova_errore_scenarios', count(*) FROM public.trova_errore_scenarios
UNION ALL SELECT 'classes', count(*) FROM public.classes
UNION ALL SELECT 'class_members', count(*) FROM public.class_members
UNION ALL SELECT 'assignments', count(*) FROM public.assignments
UNION ALL SELECT 'instructor_requests', count(*) FROM public.instructor_requests
UNION ALL SELECT 'class_messages', count(*) FROM public.class_messages
UNION ALL SELECT 'email_events', count(*) FROM public.email_events
UNION ALL SELECT 'tournament_results', count(*) FROM public.tournament_results
UNION ALL SELECT 'bbo_username_cleanup_2026_08', count(*) FROM public.bbo_username_cleanup_2026_08
UNION ALL SELECT 'bidding_sessions', count(*) FROM public.bidding_sessions
UNION ALL SELECT 'partner_profiles', count(*) FROM public.partner_profiles
UNION ALL SELECT 'club_posts', count(*) FROM public.club_posts
UNION ALL SELECT 'live_tables', count(*) FROM public.live_tables
UNION ALL SELECT 'mani_generate', count(*) FROM public.mani_generate
UNION ALL SELECT 'risultati_mano', count(*) FROM public.risultati_mano
UNION ALL SELECT 'risultati_torneo', count(*) FROM public.risultati_torneo
UNION ALL SELECT 'saved_hands', count(*) FROM public.saved_hands
UNION ALL SELECT 'scenari', count(*) FROM public.scenari
UNION ALL SELECT 'sfida_board', count(*) FROM public.sfida_board
UNION ALL SELECT 'sfide_coppie', count(*) FROM public.sfide_coppie
UNION ALL SELECT 'tornei', count(*) FROM public.tornei
UNION ALL SELECT 'torneo_mani', count(*) FROM public.torneo_mani
ORDER BY table_name;
